spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/launchpad
spring.datasource.username=launchpad
spring.datasource.password=launchpad_dev

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
